### ISSUE TITLE
Fat finger bug

### ISSUE THREAD

**Issue by Maui21** [Here-n-Now/here-n-now#33]

**Comment by chaimsash** [comment]
-Geofire end (Judah):
—map over markersArr
—group pix within x distance of each other as an object with location and an array of posts
—give that group a location and a different style pin for the map
—add an array prop to send to ViewContainer

-ViewContainer end (Chaim):
—if there is an array passed to ViewContainer
—hold that array in state
—if user clicks next or finishes their current piece of media, switch to the next piece of media in the array
—side points
——figure out how to add time left to media
——figure out how to add bullets to show how many pieces of media are left and which position you are currently in
——if it’s a video, auto play it for 10 seconds
——allow user to also click back to the previous video
